[package]
name = "codember"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "reto1"
src = "Challenge-01/main.rs" 
path = "Challenge-01/main.rs"

[dependencies]
