[alias]
reto1 = ["run", "--bin", "reto1", "--", "./Challenge-01/users.txt"]
reto2 = ["run", "--bin", "reto2"]
reto3 = ["run", "--bin", "reto3"]
reto4 = ["run", "--bin", "reto4"]
reto5 = ["run", "--bin", "reto5"]